bd/src/bd/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from crud import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^cuenta/$', views.cuenta, name='cuenta'),
    url(r'^datos/$', views.datos, name='datos'),
    url(r'^$', views.mostrar, name='mostrar'),
    url(r'^', include('crud.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bd/src/crud/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Usu(models.Model):
	id = models.AutoField(primary_key=True)
	usu = models.CharField(max_length=45)
	clave = models.CharField(max_length=45)

class DatosUsu(models.Model):
	id = models.AutoField(primary_key=True)
	nom = models.CharField(max_length=45)
	ape = models.CharField(max_length=45)
	nac = models.DateField()
	sexo = models.IntegerField()

class Cliente(models.Model):
	licencia = models.CharField(max_length=9, primary_key=True)
	nombre = models.CharField(max_length=45)
	email = models.CharField(max_length=45)
	telefono = models.CharField(max_length=45)
	password = models.CharField(max_length=45)

class Automovil(models.Model):
	matricula = models.CharField(max_length=7, primary_key=True)
	modelo = models.CharField(max_length=45)
	anno = models.IntegerField()
	precio = models.FloatField()
	foto = models.CharField(max_length=45)

class Reserva(models.Model):
	id = models.AutoField(primary_key=True)
	idCliente = models.ForeignKey(Cliente, on_delete = models.CASCADE)
	idAuto = models.ForeignKey(Automovil, on_delete = models.CASCADE)
	fechaIni = models.DateField()
	fechaFin = models.DateField()
	estado = models.IntegerField()

class Recepcionista(models.Model):
	dni = models.CharField(max_length=8, primary_key=True)
	nombre = models.CharField(max_length=45)
	password = models.CharField(max_length=45)

class RecepcionReserva(models.Model):
	id = models.AutoField(primary_key=True)
	idReserva = models.ForeignKey(Reserva, on_delete = models.CASCADE)
	idRecepcionista = models.ForeignKey(Recepcionista, on_delete = models.CASCADE)
	estado = models.IntegerField()

class Cfechas(models.Model):
	desde = models.DateField()
	hasta = models.DateField()

bd/src/crud/forms.py
from django import forms
from .models import Usu, Reserva, Cfechas
from .models import DatosUsu

BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')
class UsuForm(forms.ModelForm):
	clave = forms.CharField(widget=forms.PasswordInput)
	class Meta:
		model = Usu
		fields = ["usu", "clave"]

class DatosUsuForm(forms.ModelForm):
	class Meta:
		model = DatosUsu
		fields = ["nom", "ape","nac", "sexo"]

class ReservaForm(forms.ModelForm):
	desde = forms.CharField(widget=forms.TextInput(attrs={'class': 'datepicker'}), label="Desde")
	hasta = forms.CharField(widget=forms.TextInput(attrs={'class': 'datepicker'}), label="Hasta")
	class Meta:
		model = Cfechas
		fields = ["desde","hasta"]

class RegReservaForm(forms.ModelForm):
	class Meta:
		model = Reserva
		fields = ["idCliente", "idAuto","fechaIni", "fechaFin", "estado"]

bd/src/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="iso-8859-1">
<meta name="description" content="Ejemplo de HTML5">
<meta name="keywords" content="HTML5, CSS3, JavaScript">
<title>{% block title %}{% endblock %}</title>
<!-- Compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.9/angular.min.js"></script>
<link href="https://fonts.googleapis.com/css?family=Inconsolata" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body ng-app="myApp" ng-controller="myCtrl">
<header>

	<nav>
		<ul>
			<li><a class="nav-link" href="{% url 'datos' %}">Registrar</a>
			<li><a class="nav-link" href="{% url 'mostrar' %}">Usuarios</a>
		</ul>
	</nav>
   
</header>
<main>
	{% block contenido1 %}
	{% endblock %}
</main>
{% block angularjs %}
{% endblock %}
</body>
<style>
	main form{
		margin: 1em;
	}
    .galeria{
        display: flex;
        padding: 0.5em;
    }
    .galeria .card{
        margin:0.5em;
        width:calc((100% - 3em)/3);
    }
@media screen and (max-width: 600px) {
  .galeria{
        display: flex;
        flex-flow: wrap;
    }
    .galeria .card{
        width: 100%;
    }

}

@media screen and (min-width: 600px) {
    .frmFec{
         width:calc((100% - 3em)/3);
    }
}
p>button{
    padding: 0 !important;
}
</style>
<script>
var options = {

    format:"yyyy-mm-dd",
    autoClose: true,
    i18n: {
                months: ["Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"],
                monthsShort: ["Ene", "Feb", "Mar", "Abr", "May", "Jun", "Jul", "Ago", "Set", "Oct", "Nov", "Dic"],
                weekdays: ["Domingo","Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
                weekdaysShort: ["Dom","Lun", "Mar", "Mie", "Jue", "Vie", "Sab"],
                weekdaysAbbrev: ["D","L", "M", "M", "J", "V", "S"]
            }
 
}
document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.datepicker');
    var instances = M.Datepicker.init(elems, options);
  });
</script>
{% block js %}
{% endblock %}

</html>

bd/src/templates/datos.html
{% extends "base.html" %}
{% block title %}Registra datos{% endblock %}
{% block contenido1 %}
<form method="POST" action="." class="">{% csrf_token %}
	<div class="row">
        <div class="input-field">
          <input id="id_nom" maxlength="45" name="nom" type="text" required class="validate" />
          <label for="id_nom">Nombre</label>
        </div>
     </div>
     <div class="row">
        <div class="input-field">
          <input id="id_ape" maxlength="45" name="ape" type="text" required class="validate" />
          <label for="id_ape">Apellido</label>
        </div>
     </div>
     <div class="row">
        <div class="input-field">
          <input id="id_nac" name="nac" type="date" required />
          <label for="id_nac">Nacimiento</label>
        </div>
     </div>
     
     <div class="row">
     	<label>
      		<input class="with-gap" name="sexo" value="1" type="radio" checked />
      		<span>Hombre</span>
    	</label>
    	<label>
      		<input class="with-gap" name="sexo" value="2" type="radio"  />
      		<span>Mujer</span>
    	</label>
     </div>
<button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>
</form>
{% endblock %}

bd/src/templates/inicio.html
{% extends "base.html" %}
{% block title %}Registra seguridad{% endblock %}
{% block contenido1 %}
<form method="POST" action="." class="">{% csrf_token %}
	<div class="row">
        <div class="input-field">
          <input id="id_clave" name="clave" type="password" required class="validate" />
          <label for="id_clave">Password</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field">
          <input id="id_usu" maxlength="45" name="usu" type="text" required class="validate" />
          <label for="id_usu">Usuario</label>
        </div>
      </div>
 <button class="btn waves-effect waves-light" type="submit" name="action">Submit
    <i class="material-icons right">send</i>
  </button>
</form>
{% endblock %}

bd/src/templates/mostrar.html
{% extends "base.html" %}
{% block title %}Lista usuarios{% endblock %}
{% load staticfiles %}
{% block contenido1 %}
<form method="POST" class=" frmFec">{% csrf_token %}
  <label>Desde</label>
	<input type="text" name="" ng-model="desde">
  <label>Hasta</label>
  <input type="text" name="" ng-model="hasta">
  
 <button class="btn-floating" ng-click="buscarAuto()">
        <i class="material-icons right">search</i>
  </button>
</form>
<!--
<table>
	<thead>
		<tr>
			<td>Matrícula</td><td>Modelo</td><td>Año</td><td>Precio</td><td>foto</td><td>Reservar</td>
		</tr>
	</thead>
	<tbody>
		{% for post in titulo %} 
		<tr>
			<td>{{ post.matricula }}</td><td>{{ post.modelo }}</td><td>{{ post.anno }}</td><td>{{ post.precio }}</td><td>{{ post.foto }}</td><td><button class="btn-floating waves-effect waves-light" type="submit" name="action">
    <i class="material-icons right">add</i>
  </button></td>
		</tr>
	</tbody>
	{% endfor %}
</table>
-->

<div class="galeria"> 
<div class="card" ng-repeat="post in mdatos">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src='static/{$ post.foto $}'>
    </div>
    <div class="card-content">
    <form  method="POST">{% csrf_token %}
      <span class="card-title activator grey-text text-darken-4">{$ post.modelo $}<i class="material-icons right">more_vert</i></span>
      <p>Precio: {$ post.precio $}</p>
      <p><button class="" type="submit" name="action">
        Reservar
  </button></p>
      </form>
    </div>
    <div class="card-reveal">
    

      <span class="card-title grey-text text-darken-4">{$ post.modelo $}<i class="material-icons right">close</i></span>
      <p>Matrícula: {$ post.matricula $}</p>
      <p>Año: {$ post.anno $}</p>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
      <p></p>
      
    </div>
  </div>
<!--
<div class="galeria">
{% for post in titulo %} 
<div class="card">
    <div class="card-image waves-effect waves-block waves-light">
      <img class="activator" src='{% static post.foto %}'>
    </div>
    <div class="card-content">
    <form  method="POST">{% csrf_token %}
      <span class="card-title activator grey-text text-darken-4">{{ post.modelo }}<i class="material-icons right">more_vert</i></span>
      <p>Precio: {{ post.precio }}</p>
      <p><button class="" type="submit" name="action">
        Reservar
  </button></p>
      </form>
    </div>
    <div class="card-reveal">
    

      <span class="card-title grey-text text-darken-4">{{ post.modelo }}<i class="material-icons right">close</i></span>
      <p>Matrícula: {{ post.matricula }}</p>
      <p>Año: {{ post.anno }}</p>
      <p>Here is some more information about this product that is only revealed once clicked on.</p>
      <p></p>
      
    </div>
  </div>
  {% endfor %}
  </div>
  -->
{% endblock %}
{% block js %}
<script>

window.csrf_token = "{{ csrf_token }}";


$(function(){
 
  $("#frmBuscaAuto").on("submit",function(){
    var formData = new FormData(this);

    $.ajax({
            url : "",
            type: "POST",
            data : formData,
            processData: false,
            contentType: false,
            success:function(response){
                var message = response.content.message

                alert(message);
            },
        });
     return false;
  });
});

var app = angular.module("myApp", []);

app.config(function($httpProvider,$locationProvider,$interpolateProvider) {
    $httpProvider.defaults.headers.common["X-CSRFToken"] = window.csrf_token;

    $locationProvider.html5Mode({
              enabled:true
    });
    $interpolateProvider.startSymbol('{$');
    $interpolateProvider.endSymbol('$}');


 }); 

app.controller("myCtrl", function($scope, $http) {
 
  $scope.buscarAuto = function(){
    
    $http({
      method: 'GET',
      url: "automovil/?desde="+$scope.desde+"&hasta="+$scope.hasta
    }).then(function(response) {
      $scope.mdatos = response.data;
    
    });

  }
});
</script>
{% endblock %}
{% block angularjs %}
<script>

</script>
{% endblock %}